/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAgendaRouteImport } from './routes/admin/agenda'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin/configuracoes'
import { Route as AdminConteudoRouteImport } from './routes/admin/conteudo'
import { Route as AdminLeadsRouteImport } from './routes/admin/leads'
import { Route as AdminServicosRouteImport } from './routes/admin/servicos'
import { Route as AdminSolicitacoesRouteImport } from './routes/admin/solicitacoes'
import { Route as AdminUsuariosRouteImport } from './routes/admin/usuarios'
import { Route as ArtistasIndexRouteImport } from './routes/artistas/index'
import { Route as ArtistasSlugRouteImport } from './routes/artistas/$slug'
import { Route as AdminArtistasIndexRouteImport } from './routes/admin/artistas/index'
import { Route as AdminArtistasIdRouteImport } from './routes/admin/artistas/$id'
import { Route as AdminArtistasGerenciarRouteImport } from './routes/admin/artistas/gerenciar'
import { Route as AdminContratosIndexRouteImport } from './routes/admin/contratos/index'
import { Route as AdminContratosIdRouteImport } from './routes/admin/contratos/$id'
import { Route as AdminEditorIndexRouteImport } from './routes/admin/editor/index'
import { Route as AdminEditorPageIdRouteImport } from './routes/admin/editor/$pageId'
import { Route as AdminEditorConfiguracoesGlobaisRouteImport } from './routes/admin/editor/configuracoes-globais'
import { Route as AdminVisitantesVisitorIdRouteImport } from './routes/admin/visitantes/$visitorId'
import { Route as AdminContratosIdVisualizarRouteImport } from './routes/admin/contratos/$id.visualizar'
import { Route as AdminEditorPageIdEditSectionIdRouteImport } from './routes/admin/editor/$pageId/edit/$sectionId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendaRoute = AdminAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConteudoRoute = AdminConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicosRoute = AdminServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSolicitacoesRoute = AdminSolicitacoesRouteImport.update({
  id: '/solicitacoes',
  path: '/solicitacoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const ArtistasIndexRoute = ArtistasIndexRouteImport.update({
  id: '/artistas/',
  path: '/artistas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtistasSlugRoute = ArtistasSlugRouteImport.update({
  id: '/artistas/$slug',
  path: '/artistas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminArtistasIndexRoute = AdminArtistasIndexRouteImport.update({
  id: '/artistas/',
  path: '/artistas/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArtistasIdRoute = AdminArtistasIdRouteImport.update({
  id: '/artistas/$id',
  path: '/artistas/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArtistasGerenciarRoute = AdminArtistasGerenciarRouteImport.update({
  id: '/artistas/gerenciar',
  path: '/artistas/gerenciar',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContratosIndexRoute = AdminContratosIndexRouteImport.update({
  id: '/contratos/',
  path: '/contratos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContratosIdRoute = AdminContratosIdRouteImport.update({
  id: '/contratos/$id',
  path: '/contratos/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditorIndexRoute = AdminEditorIndexRouteImport.update({
  id: '/editor/',
  path: '/editor/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditorPageIdRoute = AdminEditorPageIdRouteImport.update({
  id: '/editor/$pageId',
  path: '/editor/$pageId',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEditorConfiguracoesGlobaisRoute =
  AdminEditorConfiguracoesGlobaisRouteImport.update({
    id: '/editor/configuracoes-globais',
    path: '/editor/configuracoes-globais',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminVisitantesVisitorIdRoute =
  AdminVisitantesVisitorIdRouteImport.update({
    id: '/visitantes/$visitorId',
    path: '/visitantes/$visitorId',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminContratosIdVisualizarRoute =
  AdminContratosIdVisualizarRouteImport.update({
    id: '/visualizar',
    path: '/visualizar',
    getParentRoute: () => AdminContratosIdRoute,
  } as any)
const AdminEditorPageIdEditSectionIdRoute =
  AdminEditorPageIdEditSectionIdRouteImport.update({
    id: '/edit/$sectionId',
    path: '/edit/$sectionId',
    getParentRoute: () => AdminEditorPageIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/artistas/$slug': typeof ArtistasSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/artistas/': typeof ArtistasIndexRoute
  '/admin/artistas/$id': typeof AdminArtistasIdRoute
  '/admin/artistas/gerenciar': typeof AdminArtistasGerenciarRoute
  '/admin/contratos/$id': typeof AdminContratosIdRouteWithChildren
  '/admin/editor/$pageId': typeof AdminEditorPageIdRouteWithChildren
  '/admin/editor/configuracoes-globais': typeof AdminEditorConfiguracoesGlobaisRoute
  '/admin/visitantes/$visitorId': typeof AdminVisitantesVisitorIdRoute
  '/admin/artistas/': typeof AdminArtistasIndexRoute
  '/admin/contratos/': typeof AdminContratosIndexRoute
  '/admin/editor/': typeof AdminEditorIndexRoute
  '/admin/contratos/$id/visualizar': typeof AdminContratosIdVisualizarRoute
  '/admin/editor/$pageId/edit/$sectionId': typeof AdminEditorPageIdEditSectionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/artistas/$slug': typeof ArtistasSlugRoute
  '/admin': typeof AdminIndexRoute
  '/artistas': typeof ArtistasIndexRoute
  '/admin/artistas/$id': typeof AdminArtistasIdRoute
  '/admin/artistas/gerenciar': typeof AdminArtistasGerenciarRoute
  '/admin/contratos/$id': typeof AdminContratosIdRouteWithChildren
  '/admin/editor/$pageId': typeof AdminEditorPageIdRouteWithChildren
  '/admin/editor/configuracoes-globais': typeof AdminEditorConfiguracoesGlobaisRoute
  '/admin/visitantes/$visitorId': typeof AdminVisitantesVisitorIdRoute
  '/admin/artistas': typeof AdminArtistasIndexRoute
  '/admin/contratos': typeof AdminContratosIndexRoute
  '/admin/editor': typeof AdminEditorIndexRoute
  '/admin/contratos/$id/visualizar': typeof AdminContratosIdVisualizarRoute
  '/admin/editor/$pageId/edit/$sectionId': typeof AdminEditorPageIdEditSectionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/artistas/$slug': typeof ArtistasSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/artistas/': typeof ArtistasIndexRoute
  '/admin/artistas/$id': typeof AdminArtistasIdRoute
  '/admin/artistas/gerenciar': typeof AdminArtistasGerenciarRoute
  '/admin/contratos/$id': typeof AdminContratosIdRouteWithChildren
  '/admin/editor/$pageId': typeof AdminEditorPageIdRouteWithChildren
  '/admin/editor/configuracoes-globais': typeof AdminEditorConfiguracoesGlobaisRoute
  '/admin/visitantes/$visitorId': typeof AdminVisitantesVisitorIdRoute
  '/admin/artistas/': typeof AdminArtistasIndexRoute
  '/admin/contratos/': typeof AdminContratosIndexRoute
  '/admin/editor/': typeof AdminEditorIndexRoute
  '/admin/contratos/$id/visualizar': typeof AdminContratosIdVisualizarRoute
  '/admin/editor/$pageId/edit/$sectionId': typeof AdminEditorPageIdEditSectionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/admin/agenda'
    | '/admin/analytics'
    | '/admin/configuracoes'
    | '/admin/conteudo'
    | '/admin/leads'
    | '/admin/servicos'
    | '/admin/solicitacoes'
    | '/admin/usuarios'
    | '/artistas/$slug'
    | '/admin/'
    | '/artistas/'
    | '/admin/artistas/$id'
    | '/admin/artistas/gerenciar'
    | '/admin/contratos/$id'
    | '/admin/editor/$pageId'
    | '/admin/editor/configuracoes-globais'
    | '/admin/visitantes/$visitorId'
    | '/admin/artistas/'
    | '/admin/contratos/'
    | '/admin/editor/'
    | '/admin/contratos/$id/visualizar'
    | '/admin/editor/$pageId/edit/$sectionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/admin/agenda'
    | '/admin/analytics'
    | '/admin/configuracoes'
    | '/admin/conteudo'
    | '/admin/leads'
    | '/admin/servicos'
    | '/admin/solicitacoes'
    | '/admin/usuarios'
    | '/artistas/$slug'
    | '/admin'
    | '/artistas'
    | '/admin/artistas/$id'
    | '/admin/artistas/gerenciar'
    | '/admin/contratos/$id'
    | '/admin/editor/$pageId'
    | '/admin/editor/configuracoes-globais'
    | '/admin/visitantes/$visitorId'
    | '/admin/artistas'
    | '/admin/contratos'
    | '/admin/editor'
    | '/admin/contratos/$id/visualizar'
    | '/admin/editor/$pageId/edit/$sectionId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/forgot-password'
    | '/reset-password'
    | '/admin/agenda'
    | '/admin/analytics'
    | '/admin/configuracoes'
    | '/admin/conteudo'
    | '/admin/leads'
    | '/admin/servicos'
    | '/admin/solicitacoes'
    | '/admin/usuarios'
    | '/artistas/$slug'
    | '/admin/'
    | '/artistas/'
    | '/admin/artistas/$id'
    | '/admin/artistas/gerenciar'
    | '/admin/contratos/$id'
    | '/admin/editor/$pageId'
    | '/admin/editor/configuracoes-globais'
    | '/admin/visitantes/$visitorId'
    | '/admin/artistas/'
    | '/admin/contratos/'
    | '/admin/editor/'
    | '/admin/contratos/$id/visualizar'
    | '/admin/editor/$pageId/edit/$sectionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ArtistasSlugRoute: typeof ArtistasSlugRoute
  ArtistasIndexRoute: typeof ArtistasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agenda': {
      id: '/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AdminAgendaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conteudo': {
      id: '/admin/conteudo'
      path: '/conteudo'
      fullPath: '/admin/conteudo'
      preLoaderRoute: typeof AdminConteudoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/servicos': {
      id: '/admin/servicos'
      path: '/servicos'
      fullPath: '/admin/servicos'
      preLoaderRoute: typeof AdminServicosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/solicitacoes': {
      id: '/admin/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/admin/solicitacoes'
      preLoaderRoute: typeof AdminSolicitacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/artistas/': {
      id: '/artistas/'
      path: '/artistas'
      fullPath: '/artistas/'
      preLoaderRoute: typeof ArtistasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artistas/$slug': {
      id: '/artistas/$slug'
      path: '/artistas/$slug'
      fullPath: '/artistas/$slug'
      preLoaderRoute: typeof ArtistasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/artistas/': {
      id: '/admin/artistas/'
      path: '/artistas'
      fullPath: '/admin/artistas/'
      preLoaderRoute: typeof AdminArtistasIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/artistas/$id': {
      id: '/admin/artistas/$id'
      path: '/artistas/$id'
      fullPath: '/admin/artistas/$id'
      preLoaderRoute: typeof AdminArtistasIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/artistas/gerenciar': {
      id: '/admin/artistas/gerenciar'
      path: '/artistas/gerenciar'
      fullPath: '/admin/artistas/gerenciar'
      preLoaderRoute: typeof AdminArtistasGerenciarRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contratos/': {
      id: '/admin/contratos/'
      path: '/contratos'
      fullPath: '/admin/contratos/'
      preLoaderRoute: typeof AdminContratosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contratos/$id': {
      id: '/admin/contratos/$id'
      path: '/contratos/$id'
      fullPath: '/admin/contratos/$id'
      preLoaderRoute: typeof AdminContratosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/editor/': {
      id: '/admin/editor/'
      path: '/editor'
      fullPath: '/admin/editor/'
      preLoaderRoute: typeof AdminEditorIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/editor/$pageId': {
      id: '/admin/editor/$pageId'
      path: '/editor/$pageId'
      fullPath: '/admin/editor/$pageId'
      preLoaderRoute: typeof AdminEditorPageIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/editor/configuracoes-globais': {
      id: '/admin/editor/configuracoes-globais'
      path: '/editor/configuracoes-globais'
      fullPath: '/admin/editor/configuracoes-globais'
      preLoaderRoute: typeof AdminEditorConfiguracoesGlobaisRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/visitantes/$visitorId': {
      id: '/admin/visitantes/$visitorId'
      path: '/visitantes/$visitorId'
      fullPath: '/admin/visitantes/$visitorId'
      preLoaderRoute: typeof AdminVisitantesVisitorIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contratos/$id/visualizar': {
      id: '/admin/contratos/$id/visualizar'
      path: '/visualizar'
      fullPath: '/admin/contratos/$id/visualizar'
      preLoaderRoute: typeof AdminContratosIdVisualizarRouteImport
      parentRoute: typeof AdminContratosIdRoute
    }
    '/admin/editor/$pageId/edit/$sectionId': {
      id: '/admin/editor/$pageId/edit/$sectionId'
      path: '/edit/$sectionId'
      fullPath: '/admin/editor/$pageId/edit/$sectionId'
      preLoaderRoute: typeof AdminEditorPageIdEditSectionIdRouteImport
      parentRoute: typeof AdminEditorPageIdRoute
    }
  }
}

interface AdminContratosIdRouteChildren {
  AdminContratosIdVisualizarRoute: typeof AdminContratosIdVisualizarRoute
}

const AdminContratosIdRouteChildren: AdminContratosIdRouteChildren = {
  AdminContratosIdVisualizarRoute: AdminContratosIdVisualizarRoute,
}

const AdminContratosIdRouteWithChildren =
  AdminContratosIdRoute._addFileChildren(AdminContratosIdRouteChildren)

interface AdminEditorPageIdRouteChildren {
  AdminEditorPageIdEditSectionIdRoute: typeof AdminEditorPageIdEditSectionIdRoute
}

const AdminEditorPageIdRouteChildren: AdminEditorPageIdRouteChildren = {
  AdminEditorPageIdEditSectionIdRoute: AdminEditorPageIdEditSectionIdRoute,
}

const AdminEditorPageIdRouteWithChildren =
  AdminEditorPageIdRoute._addFileChildren(AdminEditorPageIdRouteChildren)

interface AdminRouteChildren {
  AdminAgendaRoute: typeof AdminAgendaRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminConteudoRoute: typeof AdminConteudoRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminServicosRoute: typeof AdminServicosRoute
  AdminSolicitacoesRoute: typeof AdminSolicitacoesRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminArtistasIdRoute: typeof AdminArtistasIdRoute
  AdminArtistasGerenciarRoute: typeof AdminArtistasGerenciarRoute
  AdminContratosIdRoute: typeof AdminContratosIdRouteWithChildren
  AdminEditorPageIdRoute: typeof AdminEditorPageIdRouteWithChildren
  AdminEditorConfiguracoesGlobaisRoute: typeof AdminEditorConfiguracoesGlobaisRoute
  AdminVisitantesVisitorIdRoute: typeof AdminVisitantesVisitorIdRoute
  AdminArtistasIndexRoute: typeof AdminArtistasIndexRoute
  AdminContratosIndexRoute: typeof AdminContratosIndexRoute
  AdminEditorIndexRoute: typeof AdminEditorIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgendaRoute: AdminAgendaRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminConteudoRoute: AdminConteudoRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminServicosRoute: AdminServicosRoute,
  AdminSolicitacoesRoute: AdminSolicitacoesRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminArtistasIdRoute: AdminArtistasIdRoute,
  AdminArtistasGerenciarRoute: AdminArtistasGerenciarRoute,
  AdminContratosIdRoute: AdminContratosIdRouteWithChildren,
  AdminEditorPageIdRoute: AdminEditorPageIdRouteWithChildren,
  AdminEditorConfiguracoesGlobaisRoute: AdminEditorConfiguracoesGlobaisRoute,
  AdminVisitantesVisitorIdRoute: AdminVisitantesVisitorIdRoute,
  AdminArtistasIndexRoute: AdminArtistasIndexRoute,
  AdminContratosIndexRoute: AdminContratosIndexRoute,
  AdminEditorIndexRoute: AdminEditorIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ArtistasSlugRoute: ArtistasSlugRoute,
  ArtistasIndexRoute: ArtistasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
