/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAgendaRouteImport } from './routes/admin/agenda'
import { Route as AdminArtistasRouteImport } from './routes/admin/artistas'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin/configuracoes'
import { Route as AdminConteudoRouteImport } from './routes/admin/conteudo'
import { Route as AdminServicosRouteImport } from './routes/admin/servicos'
import { Route as AdminSolicitacoesRouteImport } from './routes/admin/solicitacoes'
import { Route as ArtistasSlugRouteImport } from './routes/artistas/$slug'
import { Route as AdminContratosIndexRouteImport } from './routes/admin/contratos/index'
import { Route as AdminContratosIdRouteImport } from './routes/admin/contratos/$id'
import { Route as AdminContratosIdVisualizarRouteImport } from './routes/admin/contratos/$id.visualizar'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAgendaRoute = AdminAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AdminRoute,
} as any)
const AdminArtistasRoute = AdminArtistasRouteImport.update({
  id: '/artistas',
  path: '/artistas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConteudoRoute = AdminConteudoRouteImport.update({
  id: '/conteudo',
  path: '/conteudo',
  getParentRoute: () => AdminRoute,
} as any)
const AdminServicosRoute = AdminServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSolicitacoesRoute = AdminSolicitacoesRouteImport.update({
  id: '/solicitacoes',
  path: '/solicitacoes',
  getParentRoute: () => AdminRoute,
} as any)
const ArtistasSlugRoute = ArtistasSlugRouteImport.update({
  id: '/artistas/$slug',
  path: '/artistas/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminContratosIndexRoute = AdminContratosIndexRouteImport.update({
  id: '/contratos/',
  path: '/contratos/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContratosIdRoute = AdminContratosIdRouteImport.update({
  id: '/contratos/$id',
  path: '/contratos/$id',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContratosIdVisualizarRoute =
  AdminContratosIdVisualizarRouteImport.update({
    id: '/visualizar',
    path: '/visualizar',
    getParentRoute: () => AdminContratosIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/artistas': typeof AdminArtistasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRoute
  '/artistas/$slug': typeof ArtistasSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/contratos/$id': typeof AdminContratosIdRouteWithChildren
  '/admin/contratos/': typeof AdminContratosIndexRoute
  '/admin/contratos/$id/visualizar': typeof AdminContratosIdVisualizarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/artistas': typeof AdminArtistasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRoute
  '/artistas/$slug': typeof ArtistasSlugRoute
  '/admin': typeof AdminIndexRoute
  '/admin/contratos/$id': typeof AdminContratosIdRouteWithChildren
  '/admin/contratos': typeof AdminContratosIndexRoute
  '/admin/contratos/$id/visualizar': typeof AdminContratosIdVisualizarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/admin/agenda': typeof AdminAgendaRoute
  '/admin/artistas': typeof AdminArtistasRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/conteudo': typeof AdminConteudoRoute
  '/admin/servicos': typeof AdminServicosRoute
  '/admin/solicitacoes': typeof AdminSolicitacoesRoute
  '/artistas/$slug': typeof ArtistasSlugRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/contratos/$id': typeof AdminContratosIdRouteWithChildren
  '/admin/contratos/': typeof AdminContratosIndexRoute
  '/admin/contratos/$id/visualizar': typeof AdminContratosIdVisualizarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/agenda'
    | '/admin/artistas'
    | '/admin/configuracoes'
    | '/admin/conteudo'
    | '/admin/servicos'
    | '/admin/solicitacoes'
    | '/artistas/$slug'
    | '/admin/'
    | '/admin/contratos/$id'
    | '/admin/contratos/'
    | '/admin/contratos/$id/visualizar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/admin/agenda'
    | '/admin/artistas'
    | '/admin/configuracoes'
    | '/admin/conteudo'
    | '/admin/servicos'
    | '/admin/solicitacoes'
    | '/artistas/$slug'
    | '/admin'
    | '/admin/contratos/$id'
    | '/admin/contratos'
    | '/admin/contratos/$id/visualizar'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/admin/agenda'
    | '/admin/artistas'
    | '/admin/configuracoes'
    | '/admin/conteudo'
    | '/admin/servicos'
    | '/admin/solicitacoes'
    | '/artistas/$slug'
    | '/admin/'
    | '/admin/contratos/$id'
    | '/admin/contratos/'
    | '/admin/contratos/$id/visualizar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  ArtistasSlugRoute: typeof ArtistasSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/agenda': {
      id: '/admin/agenda'
      path: '/agenda'
      fullPath: '/admin/agenda'
      preLoaderRoute: typeof AdminAgendaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/artistas': {
      id: '/admin/artistas'
      path: '/artistas'
      fullPath: '/admin/artistas'
      preLoaderRoute: typeof AdminArtistasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conteudo': {
      id: '/admin/conteudo'
      path: '/conteudo'
      fullPath: '/admin/conteudo'
      preLoaderRoute: typeof AdminConteudoRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/servicos': {
      id: '/admin/servicos'
      path: '/servicos'
      fullPath: '/admin/servicos'
      preLoaderRoute: typeof AdminServicosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/solicitacoes': {
      id: '/admin/solicitacoes'
      path: '/solicitacoes'
      fullPath: '/admin/solicitacoes'
      preLoaderRoute: typeof AdminSolicitacoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/artistas/$slug': {
      id: '/artistas/$slug'
      path: '/artistas/$slug'
      fullPath: '/artistas/$slug'
      preLoaderRoute: typeof ArtistasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/contratos/': {
      id: '/admin/contratos/'
      path: '/contratos'
      fullPath: '/admin/contratos/'
      preLoaderRoute: typeof AdminContratosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contratos/$id': {
      id: '/admin/contratos/$id'
      path: '/contratos/$id'
      fullPath: '/admin/contratos/$id'
      preLoaderRoute: typeof AdminContratosIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/contratos/$id/visualizar': {
      id: '/admin/contratos/$id/visualizar'
      path: '/visualizar'
      fullPath: '/admin/contratos/$id/visualizar'
      preLoaderRoute: typeof AdminContratosIdVisualizarRouteImport
      parentRoute: typeof AdminContratosIdRoute
    }
  }
}

interface AdminContratosIdRouteChildren {
  AdminContratosIdVisualizarRoute: typeof AdminContratosIdVisualizarRoute
}

const AdminContratosIdRouteChildren: AdminContratosIdRouteChildren = {
  AdminContratosIdVisualizarRoute: AdminContratosIdVisualizarRoute,
}

const AdminContratosIdRouteWithChildren =
  AdminContratosIdRoute._addFileChildren(AdminContratosIdRouteChildren)

interface AdminRouteChildren {
  AdminAgendaRoute: typeof AdminAgendaRoute
  AdminArtistasRoute: typeof AdminArtistasRoute
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminConteudoRoute: typeof AdminConteudoRoute
  AdminServicosRoute: typeof AdminServicosRoute
  AdminSolicitacoesRoute: typeof AdminSolicitacoesRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminContratosIdRoute: typeof AdminContratosIdRouteWithChildren
  AdminContratosIndexRoute: typeof AdminContratosIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAgendaRoute: AdminAgendaRoute,
  AdminArtistasRoute: AdminArtistasRoute,
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminConteudoRoute: AdminConteudoRoute,
  AdminServicosRoute: AdminServicosRoute,
  AdminSolicitacoesRoute: AdminSolicitacoesRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminContratosIdRoute: AdminContratosIdRouteWithChildren,
  AdminContratosIndexRoute: AdminContratosIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  ArtistasSlugRoute: ArtistasSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
